{% set name = "daff" %}
{% set version = "1.3.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/daff-{{ version }}.tar.gz
  sha256: 22d0da9fd6a3275b54c926a9c97b180f9258aad65113ea18f3fec52cbadcd818

build:
  noarch: python
  entry_points:
    - daff=daff:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - daff
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/paulfitz/daff
  summary: Diff and patch tables
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
