{% set name = "daff" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/daff-{{ version }}.tar.gz
  sha256: 47f0391eda7e2b5011f7ccac006b9178accb465bcb94a2c9f284257fff5d2686

build:
  noarch: python
  entry_points:
    - daff=daff:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - daff
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/paulfitz/daff
  summary: Diff and patch tables
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
